# Generated by Django 4.2.3 on 2023-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(verbose_name='Publication Date')),
                ('text', models.CharField(max_length=4000)),
                ('date_event', models.DateTimeField(verbose_name='Date of an event')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(verbose_name='Publication Date')),
                ('text', models.CharField(max_length=4000)),
            ],
        ),
    ]
