# Generated by Django 4.2.4 on 2023-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('publication_date', models.DateTimeField(verbose_name='Publication Date')),
                ('event_body', models.TextField()),
                ('date_event', models.DateTimeField(verbose_name='Date of an event')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('publication_date', models.DateTimeField(verbose_name='Publication Date')),
                ('post_body', models.TextField()),
            ],
        ),
    ]
