# Generated by Django 4.2.3 on 2023-08-01 12:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='event',
            name='event_body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
