# Generated by Django 4.2.4 on 2023-09-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
