# Generated by Django 4.2.4 on 2023-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_event_title_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_body',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_body',
            field=models.CharField(max_length=4000),
        ),
    ]
