# Generated by Django 4.2.4 on 2023-09-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_pic_alter_event_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
    ]
